### ISSUE TITLE
Error is thrown trying to count tokens for `gemini-1.5-pro-latest` model

### ISSUE THREAD

**Issue by huytool157** [google-gemini/generative-ai-js#107]
## Expected Behavior

It works

## Actual Behavior

`[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-1.5-pro-latest:countTokens: [404 Not Found] models/gemini-1.5-pro-latest is not found for API version v1, or is not supported for countTokens. Call ListModels to see the list of available models and their supported methods.`

Likely we need to change `v1` to `v1beta` somewhere before making requests to `countTokens` endpoint (the url above is still `v1`)

## Steps to Reproduce the Problem

```
const googleModel = this.client.getGenerativeModel({ model: 'gemini-1.5-pro-latest' }, { apiVersion: 'v1beta' })

await googleModel.countTokens(chunks) // error thrown here
```

## Specifications

- Version: `7.0.1`
- Platform: `macOS`

**Comment by hsubox76** [comment]
Hm, I can't seem to reproduce this. The default version was actually set to "v1beta" in 0.7.0. I tried both with and without setting the apiVersion explicitly and it worked both times.

A couple of guesses: did you upgrade from a previous version that didn't have the apiVersion option? Maybe try to clean out your node_modules/ and package-lock.json/yarn.lock files and reinstall?

Another possibility, did you do any kind of patch fix before we added apiVersion, that might still be in place?

If none of those apply, can you provide a minimal repro project?

**Comment by huytool157** [comment]
Yep looks like it, we are using `pnpm` in a monorepo so we had to re-sync the deps. Sorry for the false alarm 🤦
