### ISSUE TITLE
Add Nepali Language Support

### ISSUE THREAD

**Issue by Nirdeshyt** [google-gemini/generative-ai-js#143]
### Description of the feature request:

AI is sending no response when said to talk in Nepali. Please add that feature

**Comment by singhniraj08** [comment]
@Nirdeshyt, Thank you reporting this issue. 
This repository is for issues related to JS SDK client bugs or improvements and the client doesn't control the service's responses. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. You can also post this issue on [Discourse forum](https://discuss.ai.google.dev/).

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)

**Comment by DellaBitta** [comment]
Yes, considering this is a feature that would need to be implemented in the backend, please request the feature as described above. I'm going to close this issue for now. Thanks!
