### ISSUE TITLE
Cannot find module '@google/generative-ai/files' or its corresponding type declarations.

### ISSUE THREAD

**Issue by duccdev** [google-gemini/generative-ai-js#155]
### Description of the bug:

Hi everyone, I'm trying to import the `GoogleAIFileManager` class from `@google/generative-ai/files`
However, VSCode and the TypeScript compiler itself throws errors about the module not existing
I can import everything from `@google/generative-ai` but not `@google/generative-ai/files`

### Actual vs expected behavior:

This should import the GoogleAIFileManager class:
```ts
import { GoogleAIFileManager } from "@google/generative-ai/files";
```
I get this error:
```
Cannot find module '@google/generative-ai/files' or its corresponding type declarations.
```

### Any other information you'd like to share?

I peeked into the `node_modules` (specifically `node_modules/@google/generative-ai/files/package.json`)
On this specific line:
```json
  "name": "@google/generative-ai/files",
```
I get this warning from VSCode:
```
String does not match the pattern of "^(?:(?:@(?:[a-z0-9-*~][a-z0-9-*._~]*)?/[a-z0-9-._~])|[a-z0-9-~])[a-z0-9-._~]*$".
```
Could this be an issue when importing?

**Comment by duccdev** [comment]
I have found a workaround
Importing stuff from `@google/generative-ai/dist/src/files` instead of `@google/generative-ai/files` works
You can do this for now while this issue gets fixed

**Comment by hsubox76** [comment]
Thanks for the report, I looked into it and it seems like the name format in `node_modules/@google/generative-ai/files/package.json` is incorrect, but not what's causing the issue. The issue is the paths further down in the file are wrong - should begin with`../` and not `./`. You can actually get around this by changing your tsconfig "module" field to "node16" or similar instead of "commonjs" (which makes it rely on the top-level package.json instead, which has the right paths) but I should be able to fix this quickly.

**Comment by antoniovini47** [comment]
For those who are trying to do that recently and getting the same error. I found that Google made some changes and doesn't update some of the documentations.

You doesn't import anymore like:

`import { GoogleAIFileManager } from "@google/generative-ai/files";`

use

`import { GoogleAIFileManager } from "@google/generative-ai/server";`

instead.

Heres the only place they announced it:

![image](https://github.com/google-gemini/generative-ai-js/assets/7387249/9f7d1aa3-902c-4ea3-9eea-830edbdb8fbd)

**Comment by antoniovini47** [comment]
> when i try npm install @google/generative-ai/server i get module not found?

Just try `npm install @google/generative-ai` the folder "server" will be inside of the new installed module.

**Comment by rafael6104** [comment]
but how can import GoogleAICacheManager? in the gemini docs it says to import it like this:

import {
  FileState,
  GoogleAICacheManager,
  GoogleAIFileManager,
} from '@google/generative-ai/server';

but when i do that i always get a module not found error. my google/generative-ai is installed and working but i cant import or use the cache manager i need. i even did npm install @google/generative-ai again to see if it updated but if i try to import the cache manager from the generative-ai folder i get this error: Module '"@google/generative-ai"' has no exported member 'GoogleAICacheManager'. so i cant import generative-ai/server nor does my generative-ai package export the cache manager i need. can anyone help?

**Comment by vmss2009** [comment]
reinstall @google/generative-ai package and the problem might get resolved !

**Comment by enoshrodrigo** [comment]
> when i try npm install @google/generative-ai/server i get module not found?

I encountered the same issue when installing @google/generative-ai/server. To resolve this, I installed the latest version of the @google/generative-ai package using the following command

npm install @google/generative-ai@latest
