### ISSUE TITLE
Please add female voice option...

### ISSUE THREAD

**Issue by mjoe67886** [google-gemini/generative-ai-js#168]
### Description of the feature request:

Using Google Assistant, I've always enjoyed the female voice that was there to brighten my day period as a man.
Makes it feel like I have 2 women in my life along with Alexa on my echo dot and basically sends me to heaven period when you add a masculine voice to Gemini, even though it is. Seriously, awesome..... I absolutely cannot use it because biologically as a man. Um I can't justify it to myself...

### What problem are you trying to solve with this feature?

Making myself happier...

### Any other information you'd like to share?

This is vital to make this the first thing you change

**Comment by mjoe67886** [comment]
I know there's probably a lot of men developers on your team and when you look at it broadly for the whole world. Especially because we're trying to create world-class tools for people to use to improve the operation of the world. Not putting. The women's voice as the number one priority might seem. A little more on the less masculine side. So if you add that as quickly as possible, you're good real props from like everybody.... For example, the quick you add this the cooler overall to most people that you'll be.

**Comment by mjoe67886** [comment]
Like in the movie, Harley Davidson and the marlboro man, you know, one of their catchphrases. Was they'd rather be dead and cool, then alive and uncool.... If we apply that to this situation, we could see more awesome and manly to our wives... And the world at large...

**Comment by singhniraj08** [comment]
@mjoe67886, This repository is for issues related to Gemini Javascript SDK client bugs or improvements. Closing this issue, feel free to reopen and post your comments(if you still have queries on this). Thank you!

**Comment by Crescendo-BLYAT** [comment]
Please reopen this & ADD FEMALE VOICE!
