### ISSUE TITLE
Only works in localhost

### ISSUE THREAD

**Issue by henriqueArrazao** [google-gemini/generative-ai-js#183]
### Description of the bug:

Locally works fine and in the server not. It's not be cause of the local of the server (Germany) because I tested the Gemini request Curl in the terminal and worked.

This is the log of this package
```cmd
Server is running on port 3000 🚀
/app/node_modules/@google/generative-ai/dist/index.js:353
            throw new GoogleGenerativeAIFetchError(`Error fetching from ${url.toString()}: [${response.status} ${response.statusText}] ${message}`, response.status, response.statusText, errorDetails);
                  ^

GoogleGenerativeAIFetchError: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent: [403 Forbidden] 
    at _makeRequestInternal (/app/node_modules/@google/generative-ai/dist/index.js:353:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateCon
```tent (/app/node_modules/@google/generative-ai/dist/index.js:752:22) {
  status: 403,
  statusText: 'Forbidden',
  errorDetails: undefined
}
```
Node.js v18.20.2

The response of the raw request is this:
```html
<title>Error 403 (Forbidden)!!1</title>
<p><b>403.</b> <ins>That’s an error.</ins></p>
<p>Your client does not have permission to get URL <code>/v1beta/models/gemini-1.5-flash:generateContent</code> from this server. <ins>That’s all we know.</ins></p>
```

My instance (working fine locally):
```
const aiModel = genAI.getGenerativeModel({
  model: 'gemini-1.5-flash',
  systemInstruction: CHAT_GPT_SYSTEM_PROMPT_MESSAGE,
});
```

No idea what is going on, I've been for a while on this.

**Comment by singhniraj08** [comment]
@henriqueArrazao 
Thank you reporting this issue. 
This repository is for issues related to Dart SDK client bugs or improvements and the client doesn't control the service's responses. For issues related to Gemini API, we would suggest you to use "Send Feedback" option in [Gemini docs](https://ai.google.dev/gemini-api/docs/api-key). Ref: Screenshot below. You can also post this issue on [Discourse forum](https://discuss.ai.google.dev/).

![image](https://github.com/google/generative-ai-docs/assets/110809167/7d11fa96-c1dc-45eb-bb7c-ec8d6609c383)

**Comment by hsubox76** [comment]
> ### Description of the bug:
> Locally works fine and in the server not. It's not be cause of the local of the server (Germany) because I tested the Gemini request Curl in the terminal and worked.

Did you run the curl command while SSHd into the same server instance that you're seeing the error? Or on another machine in Germany? Can you paste the curl command? (you can obscure your API key)

**Comment by henriqueArrazao** [comment]
> > ### Description of the bug:
> > Locally works fine and in the server not. It's not be cause of the local of the server (Germany) because I tested the Gemini request Curl in the terminal and worked.
> 
> Did you run the curl command while SSHd into the same server instance that you're seeing the error? Or on another machine in Germany? Can you paste the curl command? (you can obscure your API key)

I ran in the same server instance through SSH. I'm using ChatGPT now, but here is the Curl:

```
curl --location 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent' \
--header 'content-type: application/json' \
--header 'x-goog-api-key: XXXXXXXXXXXXXXXXXXXXXXXX' \
--header 'x-goog-api-client: genai-js/0.12.0' \
--data '{
  "generationConfig": {
    "temperature": 0.5,
    "topP": 1,
    "topK": 100,
    "maxOutputTokens": 8192,
    "responseMimeType": "application/json"
  },
  "safetySettings": [],
  "systemInstruction": {
    "role": "system",
    "parts": [
      {
        "text": "make the sum"
      }
    ]
  },
  "contents": [
    {
      "parts": [
        {
          "text": "1 + 2"
        }
      ],
      "role": "user"
    }
  ]
}
'
```

**Comment by rpgramesh** [comment]
status: 400,
  statusText: 'Bad Request',
  errorDetails: [
    {
      '@type': 'type.googleapis.com/google.rpc.ErrorInfo',
      reason: 'API_KEY_INVALID',
      domain: 'googleapis.com',
      metadata: { service: 'generativelanguage.googleapis.com' }
    }
  ]

How to solve this issue ?

**Comment by nurlumeryem** [comment]
> durum: 400, durumMetni: 'Kötü İstek', hataAyrıntıları: [ { '@type': 'type.googleapis.com/google.rpc.ErrorInfo', neden: 'API_KEY_INVALID', etki alanı: 'googleapis.com', meta veri: { hizmet: 'generativelanguage.googleapis.com' } } ]
> 
> Bu sorunu nasıl çözebiliriz?

Did you find a solution? I'm facing the same issue.

**Comment by MBobyPratama** [comment]
> status: 400, statusText: 'Bad Request', errorDetails: [ { '@type': 'type.googleapis.com/google.rpc.ErrorInfo', reason: 'API_KEY_INVALID', domain: 'googleapis.com', metadata: { service: 'generativelanguage.googleapis.com' } } ]
> 
> How to solve this issue ?

did you save the api key in ` .env.local`? if so, try changing it to` .env` and don't forget to put double quotes between your api keys, and call the api key, for example:
`const genAI = new GoogleGenerativeAI(process.env.API_KEY);`
I succeeded by trying this method

**Comment by nurlumeryem** [comment]
> > status: 400, statusText: 'Bad Request', errorDetails: [ { '@type': 'type.googleapis.com/google.rpc.ErrorInfo', reason: 'API_KEY_INVALID', domain: 'googleapis.com', metadata: { service: 'generativelanguage.googleapis.com' } } ]
> > How to solve this issue ?
> 
> did you save the api key in `.env.local`? if so, try changing it to `.env` and don't forget to put double quotes between your api keys (ex: `API_KEY="YOUR_API_KEY"`), and call the api key, for example: `const genAI = new GoogleGenerativeAI(process.env.API_KEY);`
> 
> I succeeded by trying this method
Thank you for your ideas; I ended up solving it afterward and had done what you suggested

**Comment by pamorgan** [comment]
This is resolved with the api-key option
