### ISSUE TITLE
Gemini Code execution doesn't work in Typescript

### ISSUE THREAD

**Issue by olasunkanmi-SE** [google-gemini/generative-ai-js#189]
### Description of the bug:

`tools: [{codeExecution: {}},`
When I checked the package, I saw that the CodeExcutionTool interface is declared, which includes the codeExecution data type.
`export declare interface CodeExecutionTool {
    codeExecution: {};
}`
But this CodeExecutionTool is never used. I am using the Generative-ai 0.14.0 package which I believe is the latest one.

### Actual vs expected behavior:
The dataType for tools is  FunctionDeclarationsTool which doesn't include tools.
Expected behavior: The type declaration for tools should include CodeExecutionTool.

### Any other information you'd like to share?

The error message suggests that the objects in the array do not have any properties in common with the type FunctionDeclarationsTool. However, upon inspection, it appears that the objects in the array have a different structure than the expected type. Specifically, the objects in the array have a property codeExecution with an empty object {} as its value, whereas the expected type FunctionDeclarationsTool has a different structure.

**Comment by hsubox76** [comment]
It sounds like we forgot to update `Tool` to add `CodeExecutionTool` as a union member: https://github.com/google-gemini/generative-ai-js/blob/main/packages/main/types/requests.ts#L196 Will fix.
