### ISSUE TITLE
PDF not supported

### ISSUE THREAD

**Issue by haztheo** [google-gemini/generative-ai-js#201]
### Description of the bug:

GoogleGenerativeAIFetchError: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent: [400 Bad Request] Unsupported MIME type: application/pdf
```

 const result = await model.generateContent({
            contents: [
                {
                    role: "user",
                    parts: [filePart, textPart]
                },
            ],
      });
```

Docs everywhere suggest pdf is supported.

Note images work fine

### Actual vs expected behavior:
PDF support

**Comment by littlechad** [comment]
Facing the same issue

I tried uploading pdf on google ai studio and it works fine, i then use the code generated from the `Get code` button


```
const chatSession = model.startChat({
    generationConfig,
    history: [{
      role: 'user',
      parts: [{
        fileData: {
          mimeType: files[0].mimeType, << this part got the Unsupported MIME type: application/pdf error
          fileUri: files[0].uri,
        },
      }],
    }],
  })
```

**Comment by singhniraj08** [comment]
@haztheo, PDF files are currently not supported by Gemini models. Please refer to [Supported file formats](https://ai.google.dev/gemini-api/docs/prompting_with_media?lang=python#supported_file_formats) for supported file formats Gemini models. Thank you!

**Comment by logankilpatrick** [comment]
We now support PDFs and look at both the text and images : )

**Comment by PassiveFr** [comment]
> We now support PDFs and look at both the text and images : )

Hey, when will javascript files be supported?
