### ISSUE TITLE
Support for Video

### ISSUE THREAD

**Issue by e-roy** [google-gemini/generative-ai-js#34]
Will there be support to use video data like in the `@google-cloud/vertexai` library?

**Comment by intfract** [comment]
I can't wait to get support for the `video/mp4` MIME type.

**Comment by hsubox76** [comment]
Video support should be available now if you use gemini-1.5.pro-latest. For large files you can use the Files API: https://github.com/google-gemini/generative-ai-js/issues/92#issuecomment-2073657774
