### ISSUE TITLE
Issue: Improve Error Handling and Provide Detailed Error Messages

### ISSUE THREAD

**Issue by thenameisajay** [google-gemini/generative-ai-js#82]
Firstly, Thanks for the work on this library :)

### Expected Behavior

When an error occurs while using the API, the error message should be structured in a way that makes it easy to extract the reason for the failure. Currently, the error message is all squashed into one, making it tedious to get the `reason` property from the object, as shown in the following image:

![Error Message](https://github.com/google/generative-ai-js/assets/113372062/fe5b007f-63b4-4aba-9561-ddc6cdb6bc73)

Additionally, since the error is of the type `any`, it makes it difficult to tap into the reason for the failure, as shown in the following image:

![Error Type is any](https://github.com/google/generative-ai-js/assets/113372062/bced0168-a01b-48a0-b26e-380f3dd60e95)

### Workaround

To work around this issue, the user has to manually parse the error message to extract the reason for the failure, as shown in the following code snippet:

```typescript
const makeTheCall = async (
    message: object,
    apikey: string,
    generationConfig: object,
) => {
    await run(message, apikey as string, generationConfig)
        .then((response) => {
            settledState(response as string);
        })
        .catch((error) => {
            if (error.message.includes('[GoogleGenerativeAI Error]')) {
                const errorMessage = error.message;

                if (errorMessage.includes('[400 Bad Request]')) {
                    // Extract the reason for the error
                    const reasonStart = errorMessage.indexOf('reason":"') + 9;
                    const reasonEnd = errorMessage.indexOf('","domain');
                    const reason = errorMessage.substring(
                        reasonStart,
                        reasonEnd,
                    );

                    console.log('Error reason:', reason);
                }
            }
            // errorState(error.reason as string);
            throw new Error(error.message as string);
        });
};
```

This workaround allows the user to extract the reason for the failure, as shown in the following image:

![Error Reason Console logs](https://github.com/google/generative-ai-js/assets/113372062/2eb1f0a8-9e6d-402f-82bc-9117dc566107)

### Proposed Solution

To improve the error handling and provide more detailed error messages, I suggest the following:

1. Implement a custom error class that extends the built-in `Error` class and includes properties for the error code, reason, and any other relevant information.
2. When an error occurs, create an instance of the custom error class and throw it instead of the raw error object.
3. Update the error handling logic in the client code to handle the custom error class, making it easier to extract the relevant information from the error.

This approach will provide a more structured and informative error handling experience for the users of the library.

### Repo Link

The repository where I encountered this issue is [Genie](https://github.com/thenameisajay/Genie).

**Comment by SeoulSKY** [comment]
As a temporary solution, I implemented this function:

```javascript
function parseStatusCode(error: Error): number {
  const regex = /\[(\d+)[\s\w]*\]/;

  const match = regex.exec(error.message);
  if (match === null) {
    throw new SyntaxError("Couldn't parse the status code from the message: " + error.message);
  }

  return parseInt(match[1]);
}
```

This function takes the `Error` object from the library and returns the [HTTP status code](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) of the request, which helps you distinguish different kinds of errors.

Example usage:
```javascript
const genAI = GoogleGenerativeAI("invalid token");
const model = genAI.getGenerativeModel({model: "gemini-pro"});

try {
  model.generateContent("Hello world!")
catch (e) {
  const status = parseStatusCode(e);
  if (status === 400) {
    console.error("Invalid API key");
  }
  // other handlers
}
```

**Comment by hsubox76** [comment]
Consolidating additional feedback from another issue (https://github.com/google-gemini/generative-ai-js/issues/24):

> Related, it doesn't appear that I can import GoogleGenerativeAIError so that I can do `e instanceof GoogleGenerativeAIError`. Also, guidance on how to differentiate errors would be nice. Currently I don't see a way to get the HTTP status code without parsing the message (e.g. `[500 Internal Server Error]`, `[503 Service Unavailable]`).
