### ISSUE TITLE
Add support for File api

### ISSUE THREAD

**Issue by egoist** [google-gemini/generative-ai-js#92]
## Expected Behavior

The File api is only available in the python sdk: https://ai.google.dev/tutorials/prompting_with_media

## Actual Behavior

To upload file in js sdk and use it with gemini-1.5-pro

## Steps to Reproduce the Problem

none, this is a feature quest

## Specifications

- Version: 0.5.0
- Platform: web

**Comment by hsubox76** [comment]
This implementation is in progress.

**Comment by hsubox76** [comment]
This is released: https://github.com/google-gemini/generative-ai-js/releases

Sample here: https://github.com/google-gemini/generative-ai-js/blob/main/samples/node/file-upload.js

Note you have to import `GoogleAIFileManager` from a subpath, `@google/generative-ai/files`, and this is only available for Node environments (not browser).

**Comment by EvanZhouDev** [comment]
@hsubox76 It appears that when we upload a large file, the `state` of the file is still `'PROCESSING'` when it is trying to be accessed. I was wondering if there was a way with SSE to get when the state has been updated. I'm trying to do this through the REST API, but it appears that this is what this library is using under the hood, so I assume it is also applicable here.

**Comment by hsubox76** [comment]
The only solution right now is polling repeatedly with `getFile()` (or its REST equivalent) until the state becomes ACTIVE. I know this isn't ideal so feel free to create a feature request issue requesting an improvement on this, with any suggestions you have. Since this applies to the service itself, and is bigger than just one SDK, you can also try posting in https://discuss.ai.google.dev/ for more visibility.

**Comment by EvanZhouDev** [comment]
Ah, that's what I feared... thank you nonetheless! Do you have any examples of how I should do this (i.e. polling latency, how long I should poll for before aborting, etc.)?

**Comment by hsubox76** [comment]
Unfortunately I don't think we have any official suggestions for polling intervals or for how long to try before giving up. It's a pretty new feature so the documentation is lagging a bit. We should add a simple example of how to poll to the samples just so people know to do it, I'll create an issue to track.

**Comment by qingfengmy** [comment]
I have a question, Where was the file uploaded? Where can I see it？

**Comment by LindaLawton** [comment]
It's uploaded somewhere in cloud storage but its not associated with your account thats why we are not charged for the space used.

You can list the files with the API that is the only place you can see them
